// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb2UEvcaa8ZkjTkPUywLaPZHSINVgt3XA',
    appId: '1:660515093784:web:40f5cc588fe0406917326d',
    messagingSenderId: '660515093784',
    projectId: 'debermoviles3',
    authDomain: 'debermoviles3.firebaseapp.com',
    databaseURL: 'https://debermoviles3-default-rtdb.firebaseio.com',
    storageBucket: 'debermoviles3.firebasestorage.app',
    measurementId: 'G-L012P64QK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_VbRrmSgZ_RmzOGCk1cKooWG7gTh6b8E',
    appId: '1:660515093784:android:c71bede335829e2f17326d',
    messagingSenderId: '660515093784',
    projectId: 'debermoviles3',
    databaseURL: 'https://debermoviles3-default-rtdb.firebaseio.com',
    storageBucket: 'debermoviles3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb2UEvcaa8ZkjTkPUywLaPZHSINVgt3XA',
    appId: '1:660515093784:web:3d3472acd0f66e0817326d',
    messagingSenderId: '660515093784',
    projectId: 'debermoviles3',
    authDomain: 'debermoviles3.firebaseapp.com',
    databaseURL: 'https://debermoviles3-default-rtdb.firebaseio.com',
    storageBucket: 'debermoviles3.firebasestorage.app',
    measurementId: 'G-BCTLN32WZC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB6_5j8gRCuF2n3nRH9L4mec5jmakADWg',
    appId: '1:660515093784:ios:dea02d56e9ef6ea317326d',
    messagingSenderId: '660515093784',
    projectId: 'debermoviles3',
    databaseURL: 'https://debermoviles3-default-rtdb.firebaseio.com',
    storageBucket: 'debermoviles3.firebasestorage.app',
    iosBundleId: 'com.example.appCrud',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB6_5j8gRCuF2n3nRH9L4mec5jmakADWg',
    appId: '1:660515093784:ios:dea02d56e9ef6ea317326d',
    messagingSenderId: '660515093784',
    projectId: 'debermoviles3',
    databaseURL: 'https://debermoviles3-default-rtdb.firebaseio.com',
    storageBucket: 'debermoviles3.firebasestorage.app',
    iosBundleId: 'com.example.appCrud',
  );

}